#!/bin/bash

commit_msg_file=$1

commit_msg=$(cat "$commit_msg_file")

if [[ ! $commit_msg =~ ^(bugfix:|feature:)\ .+ ]]; then
    echo "Error: Commit message must start with 'bugfix: ' or 'feature: '"
    exit 1
fi
